server:
  port: 8084
spring:
  application:
    name: usvc-app-d
  cloud:
    discovery:
      enabled: true
    consul:
      enabled: true
      host: ${CONSUL_HOST:localhost}
      port: ${CONSUL_PORT:8501}
      discovery:
        enabled: true
        register: true
      config:
        enabled: false
  elasticsearch:
    rest:
      uris: localhost:9201
      connection-timeout: 1s
      read-timeout: 1m
      username: # no username
      password: # no password
  zipkin:
    baseUrl: ${JAEGER_URL:http://localhost:19411/}
management:
  endpoints:
    web:
      exposure:
        include: "*"
  endpoint:
    shutdown:
      enabled: true
