server:
  port: 8889

spring:
  profiles:
    active: native
  cloud:
    config:
      server:
        native:
          addLabelLocations: false
          searchLocations:
            - classpath:/config/{application}/{profile}
            - file:./config/{application}/{profile}
management:
  endpoints:
    web:
      exposure:
        include: "*"
  endpoint:
    shutdown:
      enabled: true
