version: '3.7'

services:
  db:
    image: postgres:12
    container_name: usvc_db
    restart: on-failure
    ports:
      - 0.0.0.0:5432:5432
    volumes:
      - ${POSTGRES_DATA_DIR}:/var/lib/postgresql/data
    environment:
      POSTGRES_DB: usvc
      POSTGRES_USER: usvc
      POSTGRES_PASSWORD: usvc
  consul:
    image: consul:1.8.3
    container_name: usvc_consul
    entrypoint: ["consul", "agent", "-dev", "--config-dir=/consul/config"]
    restart: on-failure
    stdin_open: true
    tty: true
    ports:
      - 0.0.0.0:8501:8500
      - 0.0.0.0:8601:8600
      - 0.0.0.0:8601:8600/udp
    networks:
      - usvcnet
    volumes:
      - ${CONSUL_DATA_DIR}:/consul/data
      - ${CONSUL_CONFIG_DIR}:/consul/config

networks:
  usvcnet:
    driver: bridge
