global:
  scrape_interval: 1m
  evaluation_interval: 5s
  scrape_timeout: 30s
  #query_log_file: <string>
  external_labels:
    monitor: 'codelab-monitor'
scrape_configs:
  - job_name: 'prometheus'
    scrape_interval: 5s
    static_configs:
      - targets: ['localhost:9090']
