server:
  port: 8081
spring:
  datasource:
    url: jdbc:postgresql://${POSTGRES_HOST:localhost}:${POSTGRES_PORT:5432}/${POSTGRES_DB:usvc}
    username: ${POSTGRES_USER:usvc}
    password: ${POSTGRES_PASSWORD:usvc}
  application:
    name: usvc-app-a
  liquibase:
    enabled: true
    change-log: classpath:/db/changelog/db.changelog-master.yaml
  cloud:
    discovery:
      enabled: true
    consul:
      enabled: true
      host: ${CONSUL_HOST:localhost}
      port: ${CONSUL_PORT:8501}
      discovery:
        enabled: true
        register: true
      config:
        enabled: false
management:
  endpoints:
    web:
      exposure:
        include: "*"
  endpoint:
    shutdown:
      enabled: true
logging:
  level:
    liquibase: DEBUG
