server:
  port: 8085
spring:
  application:
    name: usvc-app-e
  cloud:
    discovery:
      enabled: true
    consul:
      enabled: true
      host: ${CONSUL_HOST:localhost}
      port: ${CONSUL_PORT:8501}
      discovery:
        enabled: true
        register: true
      config:
        enabled: false
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: http://localhost:18080/auth/realms/usvc-realm
  zipkin:
    baseUrl: ${JAEGER_URL:http://localhost:19411/}
management:
  endpoints:
    web:
      exposure:
        include: "*"
  endpoint:
    shutdown:
      enabled: true
logging:
  level:
    liquibase: DEBUG

apigw:
  url: http://localhost:8081/
  token:
    url: http://localhost:18080/auth/realms/usvc-realm/protocol/openid-connect/token

insights:
  logging:
    max-payload-length: 4000
