server:
  port: 8082
spring:
  application:
    name: usvc-app-b
  cloud:
    discovery:
      enabled: true
    consul:
      enabled: true
      host: ${CONSUL_HOST:localhost}
      port: ${CONSUL_PORT:8501}
      discovery:
        enabled: true
        register: true
      config:
        enabled: false
  data:
    mongodb:
      host: localhost
      port: 30017
      username: usvc
      password: usvc123
      database: usvcdb
management:
  endpoints:
    web:
      exposure:
        include: "*"
  endpoint:
    shutdown:
      enabled: true
