apiVersion: v1
kind: Pod
metadata:
  name: usvc-demo-grafana
spec:
  hostname: usvc-grafana
  securityContext:
    runAsUser: {{ .Values.security.uid }}
    runAsGroup: {{ .Values.security.gid }}
  containers:
    - name: grafana
      image: grafana/grafana-oss:8.2.0
      ports:
        - containerPort: 3000
          hostPort: 3001
      volumeMounts:
        - mountPath: /var/lib/grafana
          name: grafana-data-dir
        - mountPath: /etc/grafana/grafana.ini
          name: grafana-config-grafanaini
        - mountPath: /etc/grafana/ldap.toml
          name: grafana-config-ldaptoml
  volumes:
    - name: grafana-data-dir
      hostPath:
        path: {{ .Values.local.volumes.path }}/grafana/data
        type: DirectoryOrCreate
    - name: grafana-config-grafanaini
      hostPath:
        path: {{ .Values.local.volumes.path }}/grafana/config/grafana.ini
        type: FileOrCreate
    - name: grafana-config-ldaptoml
      hostPath:
        path: {{ .Values.local.volumes.path }}/grafana/config/ldap.toml
        type: FileOrCreate
  restartPolicy: OnFailure
