apiVersion: apps/v1
kind: Deployment
metadata:
  name: usvc-demo-elk
spec:
  replicas: 1
  selector:
    matchLabels:
      app: ELK
  template:
    metadata:
      name: usvc-demo-mongo
      labels:
        app: ELK
    spec:
      hostname: usvc-elk-pod
      containers:
        - name: elasticsearch
          image: elasticsearch:7.9.1
          ports:
            - containerPort: 9200
            - containerPort: 9300
          volumeMounts:
            - mountPath: /usr/share/elasticsearch/data
              name: elk-data-dir
          env:
            - name: discovery.type
              value: single-node
        - name: kibana
          image: kibana:7.9.1
          ports:
            - containerPort: 5601
          volumeMounts:
            - mountPath: /usr/share/kibana/config
              name: kibana-config-dir
      volumes:
        - name: elk-data-dir
          persistentVolumeClaim:
            claimName: usvc-elk-data-pvc
        - name: kibana-config-dir
          persistentVolumeClaim:
            claimName: usvc-kibana-config-pvc
      restartPolicy: Always
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: usvc-elk-data-pvc
spec:
  storageClassName: ""
  accessModes:
    - ReadWriteOnce
  volumeName: usvc-elk-data-pv
  resources:
    requests:
      storage: 16Gi
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: usvc-kibana-config-pvc
spec:
  storageClassName: ""
  accessModes:
    - ReadWriteOnce
  volumeName: usvc-kibana-config-pv
  resources:
    requests:
      storage: 128Mi
