apiVersion: v1
kind: ConfigMap
metadata:
  name: usvc-demo-consul-config-cm
data: {{- tpl (.Files.Glob "volume/consul/config/*").AsConfig . | nindent 2}}
---
apiVersion: v1
kind: Pod
metadata:
  name: usvc-demo-consul
spec:
  containers:
    - name: consul
      image: consul:1.8.3
      ports:
        - containerPort: 8500
          hostPort: 8501
        - containerPort: 8600
          hostPort: 8601
        - containerPort: 8600
          protocol: UDP
          hostPort: 8601
      volumeMounts:
        - mountPath: /consul/data
          name: consul-data-dir
      env:
        - name: CONSUL_LOCAL_CONFIG
          valueFrom:
            configMapKeyRef:
              name: usvc-demo-consul-config-cm
              key: consul.json
  volumes:
    - name: consul-data-dir
      hostPath:
        path: {{ .Values.local.volumes.path }}/consul/data
        type: DirectoryOrCreate
  restartPolicy: OnFailure
