apiVersion: v1
kind: Service
metadata:
  name: usvc-elk
spec:
  selector:
    app: ELK
  type: NodePort
  ports:
    - name: elk-http-port
      protocol: TCP
      port: 9200
      targetPort: 9200
      nodePort: 30200
    - name: elk-binary-port
      protocol: TCP
      port: 9300
      targetPort: 9300
      nodePort: 30300
    - name: kibana-port
      protocol: TCP
      port: 5601
      targetPort: 5601
      nodePort: 30601
