apiVersion: v1
kind: Service
metadata:
  name: usvc-consul
spec:
  selector:
    app: Consul
  ports:
    - name: consul-http-port
      protocol: TCP
      port: 8500
      targetPort: 8500
    - name: consul-dns-port
      protocol: TCP
      port: 8600
      targetPort: 8600
    - name: consul-dns-port-udp
      protocol: UDP
      port: 8600
      targetPort: 8600
