apiVersion: v1
kind: PersistentVolume
metadata:
  name: usvc-elk-data-pv
spec:
  storageClassName: ""
  volumeMode: Filesystem
  capacity:
    storage: 16Gi
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain
  hostPath:
    path: {{ .Values.local.volumes.path }}/elk/data
---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: usvc-kibana-config-pv
spec:
  storageClassName: ""
  volumeMode: Filesystem
  capacity:
    storage: 128Mi
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain
  hostPath:
    path: {{ .Values.local.volumes.path }}/kibana/config
