apiVersion: v1
kind: Pod
metadata:
  name: usvc-demo-app
spec:
  containers:
    - name: db
      image: postgres:12
      ports:
        - containerPort: 5432
          hostPort: 5432
      volumeMounts:
        - mountPath: /var/lib/postgresql/data
          name: postgres-data-dir
      env:
        - name: POSTGRES_DB
          value: usvc
        - name: POSTGRES_USER
          value: usvc
        - name: POSTGRES_PASSWORD
          value: usvc
  volumes:
    - name: postgres-data-dir
      hostPath:
        path: {{ .Values.local.volumes.path }}/postgres/data
        type: DirectoryOrCreate
  restartPolicy: OnFailure
