apiVersion: v1
kind: Service
metadata:
  name: usvc-prometheus
spec:
  selector:
    app: Prometheus
  ports:
    - name: prometheus-http-port
      protocol: TCP
      port: 9090
      targetPort: 9090
