apiVersion: v1
kind: ConfigMap
metadata:
  name: usvc-demo-mongo-config-cm
data: {{- tpl (.Files.Glob "volume/mongo/config/*").AsConfig . | nindent 2}}
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: usvc-demo-mongo
spec:
  replicas: 1
  selector:
    matchLabels:
      app: Mongo
  template:
    metadata:
      name: usvc-demo-mongo
      labels:
        app: Mongo
    spec:
      hostname: usvc-mongo-pod
      containers:
        - name: mongodb
          image: mongo:4.4.1
          ports:
            - containerPort: 27017
          volumeMounts:
            - mountPath: /data/db
              name: mongo-data-dir
            - mountPath: /docker-entrypoint-initdb.d
              name: mongo-initdb-script
          env:
            - name: MONGO_INITDB_ROOT_USERNAME
              value: usvcroot
            - name: MONGO_INITDB_ROOT_PASSWORD
              value: usvcroot123
            - name: MONGO_INITDB_DATABASE
              value: usvcdb
      volumes:
        - name: mongo-data-dir
          hostPath:
            path: {{ .Values.local.volumes.path }}/mongo/data
            type: DirectoryOrCreate
        - name: mongo-initdb-script
          configMap:
            name: usvc-demo-mongo-config-cm
      restartPolicy: Always
