apiVersion: v1
kind: Service
metadata:
  name: usvc-jaeger
spec:
  selector:
    app: Jaeger
  ports:
    - name: jaeger-zipkin-thrift-port
      protocol: TCP
      port: 5775
      targetPort: 5775
    - name: jaeger-thrift-compact-port
      protocol: TCP
      port: 6831
      targetPort: 6831
    - name: jaeger-thrift-binary-port
      protocol: TCP
      port: 6832
      targetPort: 6832
    - name: jaeger-configs-port
      protocol: TCP
      port: 5778
      targetPort: 5778
    - name: jaeger-frontend-port
      protocol: TCP
      port: 16686
      targetPort: 16686
    - name: jaeger-thrift-direct-port
      protocol: TCP
      port: 14268
      targetPort: 14268
    - name: jaeger-model-proto-port
      protocol: TCP
      port: 14250
      targetPort: 14250
    - name: jaeger-zipkin-port
      protocol: TCP
      port: 9411
      targetPort: 9411
