apiVersion: v1
kind: Pod
metadata:
  name: usvc-demo-keycloak
spec:
  containers:
    - name: dbkeycloak
      image: postgres:12
      ports:
        - containerPort: 5432
          hostPort: 15432
      volumeMounts:
        - mountPath: /var/lib/postgresql/data
          name: postgres2-data-dir
      env:
        - name: POSTGRES_DB
          value: keycloak
        - name: POSTGRES_USER
          value: keycloak
        - name: POSTGRES_PASSWORD
          value: keycloak
    - name: keycloak
      image: jboss/keycloak:16.1.1
      ports:
        - containerPort: 8080
          hostPort: 18080
      env:
        - name: KEYCLOAK_USER
          value: keycloak
        - name: KEYCLOAK_PASSWORD
          value: keycloak123
        - name: DB_VENDOR
          value: postgres
        - name: DB_ADDR
          value: usvc-demo-keycloak
        - name: DB_PORT
          value: "5432"
        - name: DB_DATABASE
          value: keycloak
        #- name: DB_SCHEMA
        #  value: keycloak
        - name: DB_USER
          value: keycloak
        - name: DB_PASSWORD
          value: keycloak
  volumes:
    - name: postgres2-data-dir
      hostPath:
        path: {{ .Values.local.volumes.path }}/postgres2/data
        type: DirectoryOrCreate
  restartPolicy: OnFailure
