apiVersion: v1
kind: Pod
metadata:
  name: usvc-demo-prometheus
spec:
  hostname: usvc-prometheus
  securityContext:
    runAsUser: {{ .Values.security.uid }}
    runAsGroup: {{ .Values.security.gid }}
  containers:
    - name: prometheus
      image: prom/prometheus:v2.34.0
      ports:
        - containerPort: 9090
          hostPort: 19090
      volumeMounts:
        - mountPath: /prometheus
          name: prometheus-data-dir
        - mountPath: /etc/prometheus
          name: prometheus-config-dir
  volumes:
    - name: prometheus-data-dir
      hostPath:
        path: {{ .Values.local.volumes.path }}/prometheus/data
        type: DirectoryOrCreate
    - name: prometheus-config-dir
      hostPath:
        path: {{ .Values.local.volumes.path }}/prometheus/config
        type: DirectoryOrCreate
  restartPolicy: OnFailure
